In [1]:
import pandas as pd

demo = r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Raw Data\df_final_demo.txt"
exp = r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Raw Data\df_final_experiment_clients.txt"
webdata1 = r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Raw Data\df_final_web_data_pt_1.txt"
webdata2 = r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Raw Data\df_final_web_data_pt_2.txt"

exp_df = pd.read_csv(exp)
demo_df = pd.read_csv(demo)
webdata1_df = pd.read_csv(webdata1)
webdata2_df = pd.read_csv(webdata2)

In [2]:
web_df = pd.concat(
    [webdata1_df, webdata2_df],
    ignore_index=True
)

In [3]:
web_exp_df = web_df.merge(
    exp_df,
    on='client_id',
    how='left'
)

In [4]:
web_exp_df.shape
web_exp_df.head()
web_exp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  object
 2   visit_id      755405 non-null  object
 3   process_step  755405 non-null  object
 4   date_time     755405 non-null  object
 5   Variation     321309 non-null  object
dtypes: int64(1), object(5)
memory usage: 34.6+ MB

In [5]:
merged_df = web_exp_df.merge(
    demo_df,
    on='client_id',
    how='left'
)

In [6]:
merged_df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
merged_df.shape
merged_df.info()
merged_df.isna().sum().sort_values(ascending=False).head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         755405 non-null  int64
 1   visitor_id        755405 non-null  object
 2   visit_id          755405 non-null  object
 3   process_step      755405 non-null  object
 4   date_time         755405 non-null  object
 5   Variation         321309 non-null  object
 6   clnt_tenure_yr    449716 non-null  float64
 7   clnt_tenure_mnth  449716 non-null  float64
 8   clnt_age          449704 non-null  float64
 9   gendr             449716 non-null  object
 10  num_accts         449716 non-null  float64
 11  bal               449716 non-null  float64
 12  calls_6_mnth      449716 non-null  float64
 13  logons_6_mnth     449716 non-null  float64
dtypes: float64(7), int64(1), object(6)
memory usage: 80.7+ MB

Variation           434096
clnt_age            305701
clnt_tenure_yr      305689
clnt_tenure_mnth    305689
gendr               305689
num_accts           305689
bal                 305689
calls_6_mnth        305689
logons_6_mnth       305689
client_id                0
dtype: int64

In [8]:
merged_df['Variation'].value_counts()

Variation
Test       177847
Control    143462
Name: count, dtype: int64

In [9]:
merged_df.groupby('Variation')['client_id'].nunique()

Variation
Control    23532
Test       26968
Name: client_id, dtype: int64

In [ ]:
"""merged_df.to_csv(
    r"D:\Ironhack\project\Project-2-Vanguard-CX-Team\Data\Clean Data\merged_data_with_NaN.csv",
    index=False
)"""

In [11]:
merged_df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Who are the primary clients using this online process? primary= highest balance

#Identify Primary Clients: First, filter clients based on the highest balances. Let's assume we want the top 10%:
balance_threshold = merged_df['bal'].quantile(0.99)  # Top 1% threshold
primary_clients = merged_df[merged_df['bal'] >= balance_threshold]

primary_clients

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
809,6547909,530025328_87372984318,513826696_40872221562_614058,step_1,2017-04-12 11:07:24,Control,24.0,292.0,67.5,F,2.0,1611860.32,4.0,7.0
810,6547909,530025328_87372984318,513826696_40872221562_614058,start,2017-04-12 11:07:04,Control,24.0,292.0,67.5,F,2.0,1611860.32,4.0,7.0
895,6547909,530025328_87372984318,71985601_69714277569_550169,confirm,2017-04-07 23:04:31,Control,24.0,292.0,67.5,F,2.0,1611860.32,4.0,7.0
896,6547909,530025328_87372984318,71985601_69714277569_550169,step_3,2017-04-07 23:01:11,Control,24.0,292.0,67.5,F,2.0,1611860.32,4.0,7.0
897,6547909,530025328_87372984318,71985601_69714277569_550169,step_2,2017-04-07 23:00:06,Control,24.0,292.0,67.5,F,2.0,1611860.32,4.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750607,2515145,333655222_5880502048,335461012_42311604623_454988,step_2,2017-05-18 20:55:56,NaN,8.0,97.0,73.0,F,2.0,1606693.41,4.0,5.0
750608,2515145,333655222_5880502048,335461012_42311604623_454988,step_1,2017-05-18 20:55:22,NaN,8.0,97.0,73.0,F,2.0,1606693.41,4.0,5.0
750609,2515145,333655222_5880502048,335461012_42311604623_454988,start,2017-05-18 20:54:56,NaN,8.0,97.0,73.0,F,2.0,1606693.41,4.0,5.0
750660,2515145,333655222_5880502048,957713386_28373136764_552294,confirm,2017-05-23 23:04:15,NaN,8.0,97.0,73.0,F,2.0,1606693.41,4.0,5.0
752682,3564728,746670907_30948509483,548849601_84484099183_703674,confirm,2017-05-24 16:50:15,NaN,12.0,153.0,50.5,M,5.0,1506635.30,7.0,7.0

In [26]:
# sort by balance in descending order for clarity
primary_clients = primary_clients.sort_values(by='bal', ascending=False)

# Drop duplicates based on 'client_id' to ensure unique client IDs
primary_clients = primary_clients.drop_duplicates(subset='client_id')

primary_clients

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
412868,9286288,379581185_94472937589,701396621_7441959137_356216,step_1,2017-06-04 10:47:34,Test,21.0,254.0,62.5,M,3.0,16320040.15,6.0,9.0
255005,8339240,767840463_99901730899,458984732_28554850410_644190,confirm,2017-04-05 11:08:48,NaN,6.0,80.0,26.5,M,2.0,12838418.01,3.0,3.0
107619,7070097,123012502_20144264074,806095608_16180139947_47849,start,2017-04-07 16:20:54,Test,11.0,133.0,53.0,M,2.0,8986419.77,6.0,9.0
71715,9440656,601521757_83549490902,475431614_49219379743_79256,start,2017-04-06 09:40:41,Control,7.0,94.0,63.0,F,2.0,8292996.21,6.0,9.0
120488,2291985,45691677_55312446426,395652772_70664004028_947674,start,2017-04-08 19:43:35,Control,7.0,85.0,41.0,M,2.0,8247729.97,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57648,416724,218690351_97170467510,901955623_8525704889_940778,start,2017-03-29 16:13:17,Test,18.0,227.0,54.5,F,3.0,1451478.31,4.0,7.0
358249,7018685,573397081_76515875068,265266488_52629865834_154152,confirm,2017-06-10 10:28:15,Test,13.0,162.0,68.0,M,3.0,1450529.91,3.0,6.0
39966,512590,310197481_40958921139,907745370_53638121981_981751,confirm,2017-03-29 11:22:57,Test,29.0,352.0,49.5,M,3.0,1449979.34,4.0,7.0
52906,4055095,869395572_85259572385,963988228_85603808377_918389,step_1,2017-04-06 10:42:45,Control,48.0,576.0,64.5,M,2.0,1445198.44,4.0,8.0
308755,2425083,973235887_42418874484,293020819_63983012370_862972,confirm,2017-03-29 16:30:49,NaN,28.0,342.0,55.5,M,3.0,1444036.92,7.0,7.0

In [29]:
primary_clients[['clnt_age', 'clnt_tenure_yr', 'gendr','bal', 'num_accts']].describe()

         clnt_age  clnt_tenure_yr           bal   num_accts
count  595.000000      595.000000  5.950000e+02  595.000000
mean    58.953782       19.539496  2.457540e+06    3.048739
std     11.421189        8.410534  1.331676e+06    0.881522
min     21.500000        2.000000  1.444037e+06    2.000000
25%     51.500000       13.000000  1.665157e+06    2.000000
50%     60.500000       21.000000  2.043772e+06    3.000000
75%     67.250000       26.000000  2.751503e+06    3.500000
max     87.000000       50.000000  1.632004e+07    7.000000

In [33]:
# Calculate median for each numeric column
median_age = primary_clients['clnt_age'].median()
median_balance = primary_clients['bal'].median()
median_tenure = primary_clients['clnt_tenure_yr'].median()

# Calculate mode for each numeric column
mode_age = primary_clients['clnt_age'].mode()
mode_balance = primary_clients['bal'].mode()
mode_tenure = primary_clients['clnt_tenure_yr'].mode()

# Print outcomes
print(f"Median Age: {median_age}")
print(f"Median Balance: {median_balance}")
print(f"Median Tenure: {median_tenure}")

print("\nMode Age:")
print(mode_age)
print("\nMode Balance:")
print(mode_balance)
print("\nMode Tenure:")
print(mode_tenure)

Median Age: 60.5
Median Balance: 2043771.84
Median Tenure: 21.0

Mode Age:
0    67.5
Name: clnt_age, dtype: float64

Mode Balance:
0       1444036.92
1       1445198.44
2       1449979.34
3       1450529.91
4       1451478.31
          ...
590     8247729.97
591     8292996.21
592     8986419.77
593    12838418.01
594    16320040.15
Name: bal, Length: 595, dtype: float64

Mode Tenure:
0    22.0
Name: clnt_tenure_yr, dtype: float64

In [ ]:
"""The primary clients who have the top 1% value for balance in Vanguard are 595. 
They have an average age of 59 years old, an average tenure of 19.5 years, an average of 3 accounts, and an average balance amount of 2.457540e+06 USD. 
The youngest client is 21 years old, and the oldest one is 87 years old. 
The tenure length ranges from 2 years to 50 years. 
The minimum no of accounts is 2, and the max is 7 accounts.
Minimum balance is 1.444037e+06, max is 1.632004e+07.
75% of clients are below the age of 67, have a tenure shorter than 26 years, have a balance of less than 2.751503e+06, and have less than 4 accounts.

"""